version: '3.7'

services:

  putt-stats-frontend:
    container_name: putt-stats-frontend
    build:
      context: ./putt-stats-frontend
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      

  putt-stats-api:
    container_name: putt-stats-api
    build:
      context: ./putt-stats-api
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 8081:8081
